AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Samsung Smartthings Bathroom Automation
Resources:
  BathroomAutomation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Environment:
        Variables:
          S3_BUCKET: bathroom-automation
